//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicItem
    {
        public int ID { get; set; }
        public string ItemCatergory { get; set; }
        public string ItemCode { get; set; }
        public string Price { get; set; }
    }
}
